// axe-core scan of every main screen (WCAG 2.x A/AA + best-practice), mobile viewport.
import { launch } from './lib.mjs'
import fs from 'node:fs'
import { createRequire } from 'node:module'
const BASE = process.env.BASE_URL ?? 'http://localhost:4290'
const axeSrc = fs.readFileSync(createRequire(import.meta.url).resolve('axe-core/axe.min.js'), 'utf8')
const browser = await launch()
const page = await browser.newPage({ viewport: { width: 390, height: 844 }, reducedMotion: 'reduce' })
page.on('dialog', (d) => d.accept())
const results = {}
const scan = async (name) => {
  await page.evaluate(axeSrc)
  const r = await page.evaluate(async () => {
    const res = await window.axe.run(document, { runOnly: { type: 'tag', values: ['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa', 'wcag22aa', 'best-practice'] } })
    return res.violations.map((v) => ({ id: v.id, impact: v.impact, help: v.help, nodes: v.nodes.slice(0, 4).map((n) => ({ target: n.target.join(' '), summary: n.failureSummary?.split('\n').slice(1, 3).join(' | ') })), count: v.nodes.length }))
  })
  results[name] = r
  console.log(`\n== ${name}: ${r.length} violation types`)
  for (const v of r) {
    console.log(`  [${v.impact}] ${v.id} — ${v.help} (${v.count} nodes)`)
    for (const n of v.nodes) console.log(`      ${n.target}  ${n.summary ?? ''}`)
  }
}
await page.goto(BASE); await page.waitForSelector('input[aria-label="Choose a passphrase"]')
await scan('create-vault')
await page.fill('input[aria-label="Choose a passphrase"]', 'correct horse battery')
await page.fill('input[aria-label="Repeat passphrase"]', 'correct horse battery')
await page.click('button[type=submit]'); await page.waitForSelector('input[type=search]')
await scan('people-empty')
await page.goto(`${BASE}/#/settings`); await page.waitForSelector('h2:has-text("Sample data")')
await page.click('button:has-text("Load sample people")')
await page.waitForFunction(() => /Added/.test([...document.querySelectorAll('section')].find((s) => s.querySelector('h2')?.textContent === 'Sample data')?.querySelector('p[role="status"]')?.textContent ?? ''), null, { timeout: 60000 })
await scan('settings')
await page.goto(`${BASE}/#/`); await page.waitForSelector('.person-row'); await page.waitForTimeout(300)
await scan('people')
await page.fill('input[type=search]', 'ma'); await page.waitForTimeout(300)
await scan('people-search')
await page.fill('input[type=search]', '')
await page.locator('.person-row').nth(2).click(); await page.waitForSelector('.person h1'); await page.waitForTimeout(300)
await scan('dossier')
await page.fill('.capture-bar textarea', 'Coffee with Theo Martins and June Webb, Priya joined.')
await page.click('.capture-bar button:has-text("Save note")')
await page.waitForSelector('.looks-like').catch(() => {})
await scan('dossier-looks-like')
await page.click('.looks-like button.not-now').catch(() => {})
await page.click('.person button:has-text("Edit")'); await page.waitForSelector('.facts-form')
await scan('dossier-edit')
await page.click('.facts-form button:has-text("Cancel")').catch(() => {})
await page.click('section:has(h2:text-is("Relationships")) button:has-text("Add several")').catch(() => {})
await page.waitForSelector('.batch-panel').catch(() => {})
await scan('dossier-batch')
await page.goto(`${BASE}/#/graph`); await page.waitForSelector('canvas.graph-canvas'); await page.waitForTimeout(800)
await scan('graph')
await page.goto(`${BASE}/#/`); await page.waitForSelector('.person-row')
await page.click('.people button:has-text("Import contacts")'); await page.waitForSelector('.import-panel')
await scan('import-panel')
await page.keyboard.press('Escape')
await page.click('.people button:has-text("Add several")'); await page.waitForSelector('.batch-panel')
await scan('people-batch')
await page.keyboard.press('Escape')
await page.evaluate(() => document.activeElement?.blur?.())
await page.click('nav.tabbar button:has-text("Lock")'); await page.waitForTimeout(400)
await scan('locked')
fs.writeFileSync(new URL('./axe-results.json', import.meta.url), JSON.stringify(results, null, 2))
await browser.close()
