// Looks like people: names in a saved note become add/link offers.
import { launch } from './lib.mjs'
import fs from 'node:fs'
const BASE = process.env.BASE_URL ?? 'http://localhost:4290'
const shots = '/tmp/shots18'; fs.mkdirSync(shots, { recursive: true })
const fail = (m) => { console.error('FAIL:', m); process.exit(1) }
const browser = await launch()
const page = await browser.newPage({ viewport: { width: 390, height: 844 } })
page.on('pageerror', (e) => fail(`page error: ${e.message}`))
page.on('dialog', (d) => d.accept())
const blur = () => page.evaluate(() => document.activeElement?.blur?.())
const statusText = () => page.locator('.looks-like [role=status]').textContent()
await page.goto(BASE)
await page.fill('input[aria-label="Choose a passphrase"]', 'correct horse battery')
await page.fill('input[aria-label="Repeat passphrase"]', 'correct horse battery')
await page.click('button[type=submit]'); await page.waitForSelector('input[type=search]')

// Seed: Sam (dossier), Priya Raman (existing, to be linked by first name), two Alexes (ambiguous)
await page.click('.people button:has-text("Add several")')
await page.fill('.batch-panel textarea', 'Sam Okafor\nPriya Raman\nAlex Kim\nAlex Moreau')
await page.click('.batch-panel button[type=submit]')
await page.waitForFunction(() => /Added 4 people/.test(document.querySelector('.batch-panel .status-slot')?.textContent ?? ''))
await page.click('.batch-panel button:has-text("Done")')
await page.fill('input[type=search]', 'Sam'); await page.click('.person-row:has-text("Sam Okafor")')
await page.waitForSelector('.person h1:has-text("Sam Okafor")')

// 1. Save a note: two unknown names, one known first name, an ambiguous one, the dossier's own name, a weekday
const ta = page.locator('.capture-bar textarea')
await ta.fill('Lunch with Theo Martins and June Webb on Friday. Priya and Alex joined late, Sam paid.')
await page.click('.capture-bar button:has-text("Save note")')
await page.waitForSelector('.looks-like')
const offers = await page.locator('.looks-like li button.name .text').allTextContents()
if (offers.join('|') !== 'Theo Martins|June Webb|Priya|Alex') fail('offers: ' + offers.join('|'))
const verbs = await page.locator('.looks-like li button.name .verb').allTextContents()
if (verbs.join('|') !== 'Add|Add|Link|Link') fail('verbs: ' + verbs.join('|'))
if (await page.locator('.capture-bar .row .saved').count()) fail('Saved ✓ should yield to the card')
const all = (await page.locator('.looks-like button.all').textContent()).trim()
if (all !== 'Add & link all 3') fail('all label: ' + all)
await page.screenshot({ path: `${shots}/looks-like.png` })

// 2. Add one → person created, note rewritten to a mention, Undo offered, then Undo reverts
await page.click('.looks-like button[aria-label="Add Theo Martins as a person and link this note"]')
await page.waitForFunction(() => /Added Theo Martins/.test(document.querySelector('.looks-like [role=status]')?.textContent ?? ''))
if (!(await page.locator('.notes a:has-text("Theo Martins")').count())) fail('note should now mention Theo')
await page.click('.looks-like button.undo')
await page.waitForFunction(() => /Undone/.test(document.querySelector('.looks-like [role=status]')?.textContent ?? ''))
if (await page.locator('.notes a:has-text("Theo Martins")').count()) fail('undo should restore the plain text')
const back = await page.locator('.looks-like li button.name .text').allTextContents()
if (back[0] !== 'Theo Martins') fail('undo should re-offer: ' + back.join('|'))
console.log('add → Undo: person removed, note text restored, chip back')
await page.click('.looks-like button[aria-label="Add Theo Martins as a person and link this note"]')
await page.waitForFunction(() => /Added Theo Martins/.test(document.querySelector('.looks-like [role=status]')?.textContent ?? ''))
const left = await page.locator('.looks-like li button.name .text').allTextContents()
if (left.join('|') !== 'June Webb|Priya|Alex') fail('remaining offers: ' + left.join('|'))

// 3. Ambiguous first name → choose one
await page.click('.looks-like li.ambiguous button.name')
const choices = await page.locator('.looks-like li.choose button.name').allInnerTexts()
if (choices.length !== 2 || !/Alex Kim/.test(choices[0])) fail('choices: ' + choices.join('|'))
await page.click('.looks-like button[aria-label="Link Alex to Alex Moreau"]')
await page.waitForFunction(() => /Linked Alex Moreau/.test(document.querySelector('.looks-like [role=status]')?.textContent ?? ''))
if (!(await page.locator('.notes a:has-text("Alex Moreau")').count())) fail('note should mention Alex Moreau')
console.log('ambiguous: chose Alex Moreau')

// 4. Link existing first name; then "Not now" closes the card
await page.click('.looks-like button[aria-label="Link Priya to Priya Raman"]')
await page.waitForFunction(() => /Linked Priya Raman/.test(document.querySelector('.looks-like [role=status]')?.textContent ?? ''))
if (!(await page.locator('.notes a:has-text("Priya Raman")').count())) fail('note should mention Priya Raman')
await page.click('.looks-like button.not-now')
await page.waitForFunction(() => !document.querySelector('.looks-like'), null, { timeout: 8000 })
console.log('link: Priya → Priya Raman; Not now closed the card')
const edges = await page.locator('section:has(h2:text-is("Relationships")) .edges li').allTextContents()
for (const n of ['Theo Martins', 'Priya Raman', 'Alex Moreau']) if (!edges.some((e) => e.includes(n))) fail(`mention edge for ${n}: ` + edges)
console.log('mention edges:', edges.map((e) => e.replace(/×$/, '').trim()).join(' | '))

// 5. Declined names stay quiet for the session; Add all N
await ta.fill('Drinks with Rosa Delgado, Bruno Costa and June Webb.')
await page.click('.capture-bar button:has-text("Save note")')
await page.waitForSelector('.looks-like button.all')
const offers2 = await page.locator('.looks-like li button.name .text').allTextContents()
if (offers2.join('|') !== 'Rosa Delgado|Bruno Costa') fail('June Webb was declined this session: ' + offers2.join('|'))
const all2 = (await page.locator('.looks-like button.all').textContent()).trim()
if (all2 !== 'Add all 2') fail('all label: ' + all2)
await page.click('.looks-like button.all')
await page.waitForFunction(() => /Added 2/.test(document.querySelector('.looks-like [role=status]')?.textContent ?? ''))
if (!(await page.locator('.looks-like button.undo').count())) fail('Undo should stay available after Add all')
if ((await page.locator('.notes a:has-text("Rosa Delgado")').count()) !== 1) fail('Rosa not mentioned')
console.log('add all 2: created and mentioned; declined name not re-offered')

// 6. No card for a quiet note; card after editing an old note
await ta.fill('Quiet day, nothing new.')
await page.click('.capture-bar button:has-text("Save note")')
// The idle card (Undo only) gives way to the new note, which offers nothing.
await page.waitForFunction(() => !document.querySelector('.looks-like'), null, { timeout: 5000 })
await page.waitForSelector('.capture-bar .row .saved')
await page.click('.notes li:has-text("Quiet day") button[aria-label="Edit note"]')
await page.fill('.note-editor textarea', 'Quiet day, then Zed Quill dropped by.')
await page.click('.note-editor button:has-text("Save")')
await page.waitForSelector('.notes li .looks-like')
const edited = await page.locator('.notes li .looks-like button.name .text').allTextContents()
if (edited.join('|') !== 'Zed Quill') fail('post-edit offer: ' + edited.join('|'))
await page.click('.notes li .looks-like button.not-now')
console.log('quiet note: no card; edited note: offer inline')

// 7. People list sanity: no June Webb, one Priya, one Theo
await blur(); await page.click('nav.tabbar a:has-text("People")')
await page.fill('input[type=search]', 'Webb'); await page.waitForTimeout(150)
if (await page.locator('.person-row strong:has-text("June Webb")').count()) fail('June Webb should not exist')
await page.fill('input[type=search]', 'Theo'); await page.waitForTimeout(150)
if ((await page.locator('.person-row strong:has-text("Theo Martins")').count()) !== 1) fail('one Theo expected')

// 8. Settings toggle turns the offer off
await page.click('nav.tabbar a:has-text("Settings")')
const toggle = page.locator('label.inline-check:has-text("Suggest people") input')
if (!(await toggle.isChecked())) fail('suggestions default on')
await toggle.click(); await page.waitForFunction(() => !document.querySelector('label.inline-check input[type=checkbox]:nth-of-type(1)') || true)
await page.waitForFunction(() => [...document.querySelectorAll('label.inline-check')].find((l) => /Suggest people/.test(l.textContent))?.querySelector('input')?.checked === false)
await page.click('nav.tabbar a:has-text("People")')
await page.fill('input[type=search]', 'Sam'); await page.click('.person-row:has-text("Sam Okafor")')
await page.waitForSelector('.person h1:has-text("Sam Okafor")')
await ta.fill('Met Ada Lovelace today.')
await page.click('.capture-bar button:has-text("Save note")')
await page.waitForSelector('.capture-bar .row .saved')
if (await page.locator('.looks-like').count()) fail('offer should be off')
console.log('settings: suggestions off → no card')
await page.screenshot({ path: `${shots}/after.png` })
console.log('SMOKE16 OK')
await browser.close()
