// UX-at-scale fixes: scroll reset, store-backed paging on Back, Upcoming cap,
// letter headers, field reasons, AND search, ego default + rail collapse.
import { launch } from './lib.mjs'
const BASE = process.env.BASE_URL ?? 'http://localhost:4290'
const fail = (m) => { console.error('FAIL:', m); process.exit(1) }
const browser = await launch()
const page = await browser.newPage({ viewport: { width: 390, height: 844 }, hasTouch: true })
page.on('pageerror', (e) => fail(`page error: ${e.message}`))
page.on('dialog', (d) => d.accept())
const PASS = 'correct horse battery'
const blur = () => page.evaluate(() => document.activeElement?.blur?.())
await page.goto(BASE)
await page.fill('input[aria-label="Choose a passphrase"]', PASS)
await page.fill('input[aria-label="Repeat passphrase"]', PASS)
await page.click('button[type=submit]')
await page.waitForSelector('input[type=search]', { timeout: 15000 })
await page.goto(`${BASE}/#/settings?dev=1`)
await page.selectOption('.stress-size select', '300')
await page.click('button:has-text("Add crowd")')
await page.waitForFunction(() => /Added 300 people/.test(document.querySelector('section.stress p[role="status"]')?.textContent ?? ''), null, { timeout: 60000 })

// 1. Scroll reset on tab switch (we're scrolled deep in Settings)
await page.evaluate(() => window.scrollTo(0, document.body.scrollHeight))
await page.waitForTimeout(700)
const yBefore = await page.evaluate(() => window.scrollY)
await blur(); await page.click('nav.tabbar a:has-text("People")')
await page.waitForSelector('.person-row')
await page.waitForTimeout(100)
const yAfter = await page.evaluate(() => window.scrollY)
if (yBefore < 500 || yAfter !== 0) fail(`scroll reset: before=${yBefore} after=${yAfter}`)
console.log('tab switch resets scroll to top')

// 2. Upcoming capped at 3 with See all; list count + letter headers visible
const up = await page.locator('.upcoming li').count()
if (up !== 3) fail(`upcoming rows ${up}`)
const seeAll = page.locator('.upcoming h2 button')
console.log('upcoming capped:', up, 'rows;', (await seeAll.textContent()).trim())
await seeAll.click()
if ((await page.locator('.upcoming li').count()) <= 3) fail('see all did not expand')
await page.locator('.upcoming h2 button').click()
if (!/All people/.test(await page.locator('.list-heading').textContent())) fail('list heading')
const letters = await page.locator('li.letter').count()
if (letters < 5) fail(`letter headers ${letters}`)
console.log('list count + letter headers:', letters)

// 3. Back from a dossier keeps the grown window
await page.locator('.list-more button').click()
await page.waitForFunction(() => document.querySelectorAll('.person-row').length >= 120)
await page.locator('.list-more button').click()
await page.waitForFunction(() => document.querySelectorAll('.person-row').length >= 180)
await page.locator('.person-row').nth(150).click()
await page.waitForSelector('.person h1')
await page.click("button.back")
await page.waitForSelector('.person-row')
const rowsBack = await page.locator('.person-row').count()
if (rowsBack < 180) fail(`rows after Back: ${rowsBack}`)
console.log('Back keeps the paging window:', rowsBack, 'rows')

// 4. Field reasons + AND search
await page.fill('input[type=search]', 'Lisbon')
await page.waitForFunction(() => document.querySelectorAll('.person-row').length > 0)
const reasons = await page.locator('.person-row .snippet').allTextContents()
const rowsL = await page.locator('.person-row').count()
if (reasons.filter((r) => /in Lisbon/.test(r)).length < rowsL * 0.5) fail(`Lisbon reasons: ${reasons.length}/${rowsL}`)
console.log('field hits explain themselves:', reasons.filter((r) => /in Lisbon/.test(r)).length, 'of', rowsL)
await page.fill('input[type=search]', 'bike pump')
await page.waitForTimeout(200)
const rowsBP = await page.locator('.person-row').count()
await page.fill('input[type=search]', 'sailboat')
await page.waitForTimeout(200)
const rowsSB = await page.locator('.person-row').count()
if (rowsBP >= rowsSB + 40) fail(`AND search: "bike pump" ${rowsBP} vs sailboat ${rowsSB}`)
const snip = (await page.locator('.person-row .snippet').first().textContent())
console.log(`AND search: "bike pump" ${rowsBP} rows, sailboat ${rowsSB}; snippet: ${snip}`)
await page.fill('input[type=search]', '')

// 5. Big graph defaults to ego on me; rail collapses circles; Show everyone
await blur(); await page.click('nav.tabbar a:has-text("Graph")')
await page.waitForSelector('canvas.graph-canvas')
await page.waitForFunction(() => /focus=/.test(location.hash))
const aria1 = await page.locator('canvas.graph-canvas').getAttribute('aria-label')
if (!/Relationship graph: \d\d? people/.test(aria1)) fail('ego default: ' + aria1)
console.log('big graph opens on your connections:', aria1.split('.')[0])
const moreChip = page.locator('.chip.more')
console.log('circle chips inline, more toggle present:', await moreChip.count())
await page.click('.focus-chip button[aria-label*="show everyone"]')
await page.waitForFunction(() => /all=1/.test(location.hash))
await page.waitForSelector('.graph-status')
console.log('status while arranging:', (await page.locator('.graph-status').textContent()).trim())
const legend = await page.locator('.graph-legend').textContent()
if (!/zoom in to see names/i.test(legend)) fail('big-graph legend: ' + legend)
if ((await moreChip.count()) !== 1) fail('more chip missing on full graph')
await moreChip.click()
const chips = await page.locator('.chip.circle-filter').count()
if (chips !== 20) fail(`expanded circle chips ${chips}`)
console.log('rail: +more expands to', chips, 'circle chips; legend:', legend.slice(0, 40))
await page.waitForSelector('canvas.graph-canvas[data-layout="settled"]', { timeout: 60000 })
if (await page.locator('.graph-status').count()) fail('status still shown after settle')
console.log('SMOKE12 OK')
await browser.close()
