// Person picker typeahead: relationship form, compare-with, circle add.
import { launch } from './lib.mjs'
import fs from 'node:fs'
const BASE = process.env.BASE_URL ?? 'http://localhost:4290'
const shots = '/tmp/shots15'; fs.mkdirSync(shots, { recursive: true })
const fail = (m) => { console.error('FAIL:', m); process.exit(1) }
const browser = await launch()
const page = await browser.newPage({ viewport: { width: 390, height: 844 } })
page.on('pageerror', (e) => fail(`page error: ${e.message}`))
page.on('dialog', (d) => d.accept())
const blur = () => page.evaluate(() => document.activeElement?.blur?.())
await page.goto(BASE)
await page.fill('input[aria-label="Choose a passphrase"]', 'correct horse battery')
await page.fill('input[aria-label="Repeat passphrase"]', 'correct horse battery')
await page.click('button[type=submit]')
await page.waitForSelector('input[type=search]', { timeout: 15000 })
await page.goto(`${BASE}/#/settings`)
await page.click('button:has-text("Load sample people")')
await page.waitForFunction(() => /Added/.test([...document.querySelectorAll('section')].find((s) => s.querySelector('h2')?.textContent === 'Sample data')?.querySelector('p[role="status"]')?.textContent ?? ''), null, { timeout: 30000 })
// Open Grace Liu
await blur(); await page.click('nav.tabbar a:has-text("People")')
await page.fill('input[type=search]', 'Grace'); await page.click('.person-row:has-text("Grace Liu")')
await page.waitForSelector('.person h1:has-text("Grace Liu")')
// No native person select anywhere on the page
if (await page.locator('select[aria-label="Person"]').count()) fail('native person select still present')
// Typeahead: type, arrow, enter
const picker = page.locator('input[aria-label="Person"]')
await picker.click()
if (!(await page.locator('.chip-suggestions').count())) fail('list should open on focus')
const onFocus = await page.locator('.chip-suggestions li[role="option"]').count()
if (await page.locator('.chip-suggestions li[aria-selected="true"]').count()) fail('nothing should be auto-selected on focus')
// Enter with nothing highlighted and nothing typed does nothing
await page.keyboard.press('Enter')
if (await page.locator('form.add-form .picked-chip').count()) fail('Enter on an untyped field picked someone')
// Tab never picks; it just moves on
await picker.fill('sam'); await page.keyboard.press('Tab')
if (await page.locator('form.add-form .picked-chip').count()) fail('Tab picked a person')
if (await page.locator('.chip-suggestions').count()) fail('Tab should close the list')
await picker.click()
// Escape: first closes the list, second clears the query
await picker.fill('sam'); await page.keyboard.press('Escape')
if (await page.locator('.chip-suggestions').count()) fail('Escape should close the list')
await page.keyboard.press('Escape')
if ((await picker.inputValue()) !== '') fail('second Escape should clear the query')
// No duplicate offer for the page's own person; no-match message
await picker.fill('Grace Liu')
if (await page.locator('.chip-suggestions li:has-text("+ Add")').count()) fail('offered to create a duplicate of the page person')
if (!(await page.locator('.picker-empty').count())) fail('no-match message missing')
await picker.fill('ma')
const names = await page.locator('.chip-suggestions .picker-name').allInnerTexts()
if (!/^Marcus Webb/.test(names[0])) fail('ranking: ' + names.join('|'))
if (!(await page.locator('.chip-suggestions li[aria-selected="true"]').count())) fail('typing should highlight the top match')
await page.keyboard.press('ArrowDown'); await page.keyboard.press('ArrowUp')
await page.keyboard.press('Enter')
const chip = await page.locator('form.add-form .picked-chip').textContent()
if (!/Marcus Webb/.test(chip)) fail('picked chip: ' + chip)
// Enter-pick with no type chosen routes focus to the type select (name, Enter, Enter loop)
await page.waitForFunction(() => document.activeElement?.getAttribute('aria-label') === 'Relationship type')
console.log('typeahead: list on focus (' + onFocus + '), Tab/Escape/duplicate guards, "ma" →', names[0].split('\n')[0], '→ type select focused')
await page.screenshot({ path: `${shots}/picker-chip.png` })
// Enter must not have submitted the form (no type chosen yet)
if (await page.locator('.edges li:has-text("Marcus Webb")').count()) fail('form submitted early')
await page.selectOption('select[aria-label="Relationship type"]', { label: 'coworker' })
if (await page.locator('form.add-form .picked-chip').count() !== 1) fail('chip lost after choosing a type')
await page.click('form.add-form:has(.person-picker) button[type=submit]')
await page.waitForSelector('.edges li:has-text("Marcus Webb")')
if (await page.locator('form.add-form .picked-chip').count()) fail('picker should reset after adding')
console.log('relationship added via the picker; picker reset')
// Change mind: pick then clear
await picker.fill('sam'); await page.click('.chip-suggestions li:has-text("Sam Kim")')
await page.click('form.add-form .picked-chip button[aria-label^="Change person"]')
await page.waitForSelector('input[aria-label="Person"]:focus')
console.log('× on the chip returns to typing with focus')
// Create a new person from the picker
await picker.fill('Nadia Fresh')
await page.click('.chip-suggestions li:has-text("+ Add “Nadia Fresh”")')
await page.waitForSelector('form.add-form .picked-chip:has-text("Nadia Fresh")')
await page.selectOption('select[aria-label="Relationship type"]', { label: 'friend' })
await page.click('form.add-form:has(.person-picker) button[type=submit]')
await page.waitForSelector('.edges li:has-text("Nadia Fresh")')
console.log('new person created from the picker and linked')
await page.screenshot({ path: `${shots}/picker-list.png` })
// Compare-with picker
if (!(await page.locator('.compare-with .picked-chip:has-text("You")').count())) fail('compare default should show a "You" chip')
await page.click('.compare-with .picked-chip button')
const cmp = page.locator('input[aria-label="Compare mutual connections with"]')
await cmp.fill('priya'); await page.click('.chip-suggestions li:has-text("Priya Raman")')
await page.waitForSelector('.compare-with .picked-chip:has-text("Priya Raman")')
console.log('compare-with: "You" chip → change → picker')
// Circle peek picker on the graph
await blur(); await page.goto(`${BASE}/#/graph`)
await page.waitForSelector('canvas.graph-canvas')
await page.click('.chip-group:has-text("Climbing crew") button.chip-edit')
await page.waitForSelector('.circle-peek')
const before = await page.locator('.circle-peek .member').count().catch(() => 0)
await page.fill('.circle-peek input[role="combobox"]', 'gra')
const listBox = await page.locator('.circle-peek .chip-suggestions').boundingBox()
const inputBox = await page.locator('.circle-peek input[role="combobox"]').boundingBox()
if (!(listBox.y + listBox.height <= inputBox.y + 1)) fail('circle list should open above the field')
// Escape closes only the list, not the card
await page.keyboard.press('Escape')
if (!(await page.locator('.circle-peek').count())) fail('Escape closed the whole peek card')
// Same value again fires no input event; ArrowDown reopens the list.
await page.keyboard.press('ArrowDown')
await page.waitForSelector('.circle-peek .chip-suggestions')
await page.screenshot({ path: `${shots}/circle-picker.png` })
await page.click('.circle-peek .chip-suggestions li:has-text("Grace Liu")')
await page.waitForFunction(() => /Grace/.test(document.querySelector('.circle-peek')?.textContent ?? ''), null, { timeout: 5000 })
console.log('circle peek: list opens upward, Escape keeps the card, member added (before:', before, ')')
if (await page.locator('.circle-peek input[role="combobox"]').inputValue() !== '') fail('circle picker should clear after adding')
console.log('SMOKE14 OK')
await browser.close()
