// Add several: People page batch, dossier batch with types, keep-adding form.
import { launch } from './lib.mjs'
import fs from 'node:fs'
const BASE = process.env.BASE_URL ?? 'http://localhost:4290'
const shots = '/tmp/shots17'; fs.mkdirSync(shots, { recursive: true })
const fail = (m) => { console.error('FAIL:', m); process.exit(1) }
const browser = await launch()
const page = await browser.newPage({ viewport: { width: 390, height: 844 } })
page.on('pageerror', (e) => fail(`page error: ${e.message}`))
page.on('dialog', (d) => d.accept())
const blur = () => page.evaluate(() => document.activeElement?.blur?.())
await page.goto(BASE)
await page.fill('input[aria-label="Choose a passphrase"]', 'correct horse battery')
await page.fill('input[aria-label="Repeat passphrase"]', 'correct horse battery')
await page.click('button[type=submit]'); await page.waitForSelector('input[type=search]')

// 1. People page: paste a list
await page.click('.people button:has-text("Add several")')
await page.waitForSelector('.batch-panel')
await page.fill('.batch-panel textarea', 'Sam Okafor\nPriya Raman, Theo Martins\n\nsam okafor')
await page.waitForSelector('.batch-preview li')
const preview = await page.locator('.batch-preview li .name').allTextContents()
if (preview.join('|') !== 'Sam Okafor|Priya Raman|Theo Martins') fail('preview: ' + preview)
const btn = await page.locator('.batch-panel button[type=submit]').textContent()
if (!/Add 3/.test(btn)) fail('button label: ' + btn)
await page.screenshot({ path: `${shots}/batch-people.png` })
await page.click('.batch-panel button[type=submit]')
await page.waitForFunction(() => /Added 3 people/.test(document.querySelector('.batch-panel .status-slot')?.textContent ?? ''))
console.log('People page batch:', (await page.locator('.batch-panel .status-slot').textContent()).trim())
await page.click('.batch-panel button:has-text("Done")')
if (await page.locator('.batch-panel').count()) fail('panel should close on Done')
await page.waitForFunction(() => document.querySelectorAll('.person-row').length >= 4)
// Existing names are skipped on the People page
await page.click('.people button:has-text("Add several")')
await page.fill('.batch-panel textarea', 'Sam Okafor')
await page.waitForSelector('.batch-preview .tag.known')
if (!(await page.locator('.batch-panel button[type=submit]').isDisabled())) fail('nothing new → button should be disabled')
console.log('existing name on People page: skipped, nothing to add')
await page.click('.batch-panel button:has-text("Cancel")')

// 2. Dossier batch with per-line types, a directed type, an existing person, an unknown type
await page.fill('input[type=search]', 'Sam'); await page.click('.person-row:has-text("Sam Okafor")')
await page.waitForSelector('.person h1:has-text("Sam Okafor")')
await page.click('section:has(h2:text-is("Relationships")) button:has-text("Add several")')
await page.waitForSelector('.batch-panel')
await page.fill('.batch-panel textarea', 'Priya Raman — coworker\nJune Webb — parent of\nRosa Delgado — landlord\nBruno Costa')
await page.waitForSelector('.batch-preview li:nth-child(4)')
const known = await page.locator('.batch-preview li:has-text("Priya Raman") .tag').textContent()
if (!/will link/.test(known)) fail('existing person should link: ' + known)
if (!(await page.locator('.batch-preview .hint:has-text("isn\'t a type")').count())) fail('unknown type hint missing')
await page.screenshot({ path: `${shots}/batch-dossier.png` })
await page.click('.batch-panel button[type=submit]')
await page.waitForFunction(() => /Added 3 people, linked 4/.test(document.querySelector('.batch-panel .status-slot')?.textContent ?? ''))
console.log('dossier batch:', (await page.locator('.batch-panel .status-slot').textContent()).trim())
await page.click('.batch-panel button:has-text("Done")')
const edges = await page.locator('.edges li').allTextContents()
if (!edges.some((e) => /Priya Raman/.test(e) && /coworker/.test(e))) fail('Priya coworker edge: ' + edges)
if (!edges.some((e) => /June is parent of Sam/.test(e))) fail('directed reading: ' + edges)
if (!edges.some((e) => /Rosa Delgado/.test(e) && /friend/.test(e))) fail('unknown type → default friend: ' + edges)
if (!edges.some((e) => /Bruno Costa/.test(e) && /friend/.test(e))) fail('no type → default: ' + edges)
console.log('edges:', edges.map((e) => e.replace(/×$/, '').trim()).join(' | '))
// No duplicate Priya
await blur(); await page.click('nav.tabbar a:has-text("People")'); await page.fill('input[type=search]', 'Priya')
await page.waitForTimeout(200)
if ((await page.locator('.person-row:has-text("Priya Raman")').count()) !== 1) fail('duplicate Priya')
console.log('existing people linked, not duplicated')

// 3. Keep adding: type stays, caret returns quietly
await page.fill('input[type=search]', 'Theo'); await page.click('.person-row:has-text("Theo Martins")')
await page.waitForSelector('.person h1:has-text("Theo Martins")')
const picker = page.locator('input[aria-label="Person"]')
await picker.fill('Sam'); await page.click('.chip-suggestions li:has-text("Sam Okafor")')
await page.selectOption('select[aria-label="Relationship type"]', { label: 'coworker' })
await page.click('form.add-form:has(.person-picker) button[type=submit]')
await page.waitForSelector('.edges li:has-text("Sam Okafor")')
const typeAfter = await page.locator('select[aria-label="Relationship type"] option:checked').textContent()
if (typeAfter !== 'coworker') fail('type should persist: ' + typeAfter)
const focused = await page.evaluate(() => document.activeElement?.getAttribute('aria-label'))
if (focused !== 'Person') fail('focus should return to the person field: ' + focused)
if (await page.locator('form.add-form .chip-suggestions').count()) fail('list should stay closed on quiet refocus')
await page.keyboard.type('Pri'); await page.click('.chip-suggestions li:has-text("Priya Raman")')
await page.click('form.add-form:has(.person-picker) button[type=submit]')
await page.waitForSelector('.edges li:has-text("Priya Raman")')
console.log('keep adding: type persisted, quiet refocus, second link added')
console.log('SMOKE15 OK')
await browser.close()
